name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  test-unit:
    name: unit tests

    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          package-manager-cache: false

      - name: Setup pnpm
        run: corepack enable

      - name: Get pnpm cache directory
        shell: bash
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> ${GITHUB_ENV}

      - name: Use pnpm cache
        uses: actions/cache@v6
        with:
          path: ${{ env.pnpm_cache_dir }}
          key: ubuntu-24.04-arm-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ubuntu-24.04-arm-node-

      - name: Install pnpm dependencies
        id: install-pnpm
        run: timeout 300 pnpm install --color=always --prefer-offline --frozen-lockfile
        continue-on-error: true

      - name: Install pnpm dependencies (retry)
        if: steps.install-pnpm.outcome == 'failure'
        run: timeout 300 pnpm install --color=always --prefer-offline --frozen-lockfile

      - name: Run unit tests
        run: pnpm --color=always --stream test:unit
